### PR TITLE
Add option to disable namespace validation

### LINKED ISSUE #59: Allow switching namespaces without trying to list them
I am connecting to some clusters where I don't have the right to switch namespaces, so I expect `kubie ns` by itself to not work. However, I think that `kubie ns NAMESPACE` should work without trying to list the namespaces. Right now it fails with:

```
Error: Error calling kubectl: Error from server (Forbidden): namespaces is forbidden: User "SOME-USER" cannot list resource "namespaces" in API group "" at the cluster scope
```

### PR DESCRIPTION
**Pull request by sbstp**
Fixes #59

### CODE REVIEW

**Comment by sbstp** [comment]
@rombert works for you?

**Comment by rombert** [comment]
Thanks for preparing the changes, @sbstp ! With the PR applied, `kubie ctx -n $NS $CTX` works, but `kubie ctx $CTX` followed by `kubie ns $NS` does not. The error is the same: 

> User ... cannot list resource "namespaces" in API group "" at the cluster scope

**Comment by sbstp** [comment]
Thanks for testing, there was indeed an issue with the code. Can you try again?

**Comment by rombert** [comment]
It works perfectly now, thanks @sbstp !

**Pull request merged**
