### PR TITLE
Avoid using temporary file for state

### LINKED ISSUE #73: Invalid cross-device link with `kubie ns`
My Fedora 33 system defaults to `/tmp` being a `tmpfs` filesystem, causing:
```
$ kubie ns default
Error: Failed to write state to '/home/parse/.local/share/kubie/state.json'

Caused by:
    0: failed to persist temporary file: Invalid cross-device link (os error 18)
    1: Invalid cross-device link (os error 18)
```
Curiously, I still get an error with `TMPDIR=<foo> kubie ...`:
```
$ TMPDIR=/home/parse/tmp kubie ns default
Error: failed to persist temporary file: Invalid cross-device link (os error 18)

Caused by:
    Invalid cross-device link (os error 18)
```

### PR DESCRIPTION
**Pull request by sbstp**
Fixes: #73

### CODE REVIEW

**Comment by sbstp** [comment]
@TyBrown can you test this branch in parallel as well? Had to make a few changes.

**Comment by TyBrown** [comment]
> @TyBrown can you test this branch in parallel as well? Had to make a few changes.

Absolutely! I'll test this out tomorrow morning on my work computer.

I was just learning about this Guard/Drop-pattern in Rust too, so this gives a good example to learn from! :)

**Comment by sbstp** [comment]
This is kind of a half-assed guard implementation. Usually the guard is a smart pointer that controls access to the resource the lock protects. So a proper lock guard would own the file it is protecting and only let you access the file while the lock has not been released.

**Comment by TyBrown** [comment]
@sbstp This locking doesn't appear to be working... parallel sessions will corrupt the statefile with this patch.

**Comment by TyBrown** [comment]
LGTM! I've tested these updates in parallel on Mac and they seem to work fine. Thanks for cleaning up the fantastic mess I seem to have made of this code. Hopefully this is the last of it!

**Pull request merged**
