### PR TITLE
feat: Add support for nushell

### LINKED ISSUE #121: Please support nushell
nushell is available here: https://www.nushell.sh/

```
$ kubie ctx
Error: Could not detect shell in use
```

### PR DESCRIPTION
**Pull request by Miuler**
Add basic support for nushell

Resolve #121

### CODE REVIEW

**Comment by sbstp** [comment]
The prompt does not work in nushell

**Comment by Miuler** [comment]
> The prompt does not work in nushell


This pull request adds basic support for nushell. I use the starship, so I didn't need to change the native prompt in nushell XD. Do you need a support prompt to approve this PR?

**Comment by Miuler** [comment]
I have added support for prompt in nushell

**Comment by Miuler** [comment]
I fixed the `remove_matchess` problem. It's unstable because it's a new API, but I replaced it with a function called `reclace`.

**Comment by Miuler** [comment]
Please @sbstp, can you Review this pull?

**Comment by Miuler** [comment]
@sbstp, what is needed to approve this pull request?

**Comment by Miuler** [comment]
I think you are too busy to answer :(

**Comment by Miuler** [comment]
@sbstp, what is needed to approve this pull request? It has been two months

**Pull request merged**
